// build.zig — Zig's build system configuration.
//
// Unlike C/C++ Makefiles or Node's package.json scripts, Zig's build system
// is itself written in Zig. The `zig build` command looks for this file and
// calls the `build` function below.

const std = @import("std");

// This function is called by `zig build`. The `b` parameter is a pointer
// to a Build object — think of it like a build recipe builder.
pub fn build(b: *std.Build) void {
    // target: what platform to compile for.
    // By defaulting to `b.standardTargetOptions()`, it uses the host machine
    // but can be overridden with `zig build -Dtarget=x86_64-linux`.
    const target = b.standardTargetOptions(.{});

    // optimize: debug, release-safe, release-fast, or release-small.
    // Debug is the default — gives us safety checks and stack traces.
    const optimize = b.standardOptimizeOption(.{});

    // --- Build-time version stamping ---------------------------------
    // Run `git describe` at build time and bake the result into a
    // generated src/version.zig that the rest of the codebase imports.
    // This is what lets a tester run `ms365-mcp --version` (or read
    // serverInfo.version on initialize) and see exactly which commit
    // is on disk — no more "did Rohit pull the staging build or the
    // March one?" guessing games.
    const version = computeVersion(b);
    const version_src = b.fmt(
        \\// AUTO-GENERATED by build.zig — do not edit by hand.
        \\// The string here is computed from `git describe` at build time
        \\// and is what `ms365-mcp --version` and serverInfo.version report.
        \\pub const VERSION = "{s}";
        \\
    , .{version});
    const version_wf = b.addWriteFiles();
    const version_path = version_wf.add("version.zig", version_src);

    // In Zig 0.16, executables are built from a Module. A module groups
    // source files + target + optimization level together.
    // "src/main.zig" is the root — Zig follows all @import()s from there.
    const exe = b.addExecutable(.{
        .name = "ms365-mcp",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    // Make `@import("version")` resolve to the generated file. The
    // import name is what main.zig will ask for; the path is the
    // build-system-managed file we just generated.
    exe.root_module.addAnonymousImport("version", .{
        .root_source_file = version_path,
    });

    // Tell the build system to install the binary into zig-out/bin/
    // when the user runs `zig build`.
    b.installArtifact(exe);

    // Add a `zig build run` command that builds AND runs the binary.
    // Handy for testing during development.
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());

    // Wire it up so `zig build run` works.
    const run_step = b.step("run", "Run the MCP server");
    run_step.dependOn(&run_cmd.step);

    // Add a `zig build test` command that runs all inline test blocks.
    // Zig discovers tests transitively through @import chains from the root.
    const unit_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    unit_tests.root_module.addAnonymousImport("version", .{
        .root_source_file = version_path,
    });
    const run_tests = b.addRunArtifact(unit_tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_tests.step);

    // Add a `zig build e2e` command that builds and runs end-to-end tests.
    // This spawns the MCP server as a child process and tests the full
    // JSON-RPC protocol against the live Microsoft Graph API.
    const e2e_exe = b.addExecutable(.{
        .name = "e2e",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/e2e.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    e2e_exe.root_module.addAnonymousImport("version", .{
        .root_source_file = version_path,
    });
    b.installArtifact(e2e_exe);

    const e2e_cmd = b.addRunArtifact(e2e_exe);
    e2e_cmd.step.dependOn(b.getInstallStep());
    const e2e_step = b.step("e2e", "Run end-to-end tests against live Graph API");
    e2e_step.dependOn(&e2e_cmd.step);
}

/// Compute a version string at build time using `git describe`. Falls
/// back to a hardcoded base version if the build is happening outside
/// a git checkout (e.g. someone vendored the source tarball).
///
/// Examples of what this returns:
///   "v0.2.0"                  — exact tag, clean tree
///   "v0.2.0-3-g61cb00e"        — 3 commits past v0.2.0
///   "v0.2.0-3-g61cb00e-dirty"  — 3 commits past v0.2.0, working tree dirty
///   "v0.2.0"                  — fallback when not in a git checkout
fn computeVersion(b: *std.Build) []const u8 {
    const fallback = "v0.2.0";

    // b.runAllowFail captures stdout on success or returns an error. We
    // pass --tags so non-annotated tags work too, --always so we get a
    // SHA when there's no tag yet, --dirty to mark uncommitted changes.
    var exit_code: u8 = 0;
    const stdout = b.runAllowFail(
        &[_][]const u8{ "git", "describe", "--tags", "--always", "--dirty" },
        &exit_code,
        .ignore,
    ) catch return fallback;
    defer b.allocator.free(stdout);

    if (exit_code != 0) return fallback;
    // git's stdout has a trailing newline — trim it.
    const trimmed = std.mem.trimEnd(u8, stdout, "\n\r \t");
    if (trimmed.len == 0) return fallback;
    return b.allocator.dupe(u8, trimmed) catch fallback;
}
